version: "3"
services:
  nodecg:
    build: .
    volumes:
      - "./cfg:/nodecg/cfg:rw"
      - "assets:/nodecg/assets:rw"
      - "db:/nodecg/db:rw"
      - "./graphics:/nodecg/bundles/gunma-rta-layouts/graphics:ro"
      - "./extension:/nodecg/bundles/gunma-rta-layouts/extension:ro"
      - "./schemas:/nodecg/bundles/gunma-rta-layouts/schemas:ro"
      - "./shared:/nodecg/bundles/gunma-rta-layouts/shared:ro"
      - "./node_modules:/nodecg/bundles/gunma-rta-layouts/node_modules:ro"
      - "./package.json:/nodecg/bundles/gunma-rta-layouts/package.json:ro"
    ports:
      - "9090:9090"

volumes:
  db:
  assets:
  node_modules:
